spring:
  application:
    name: auth-service
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:https://}
  cloud:
    config:
      name: ${spring.application.name}, common
      profile: ${spring.profiles.active}
